### ISSUE TITLE
Finalize page layouts & hifi-design for all major Portals Pages

### ISSUE THREAD

**Issue by gggodhwani** [cbgaindia/portal-design#4]
- [ ] Home Page
- [ ] Organization/Department Page
- [ ] Datasets Landing Page
- [ ] Datasets details page - Visualize, Download, etc
- [ ] Sector Landing Page

**Comment by SuchismitaNaik** [comment]
![homepage_iteration1](https://cloud.githubusercontent.com/assets/16536382/15052967/ed5788a6-131d-11e6-976b-026ff1181bbb.jpg)
Home page with the theme colour as Light Black. And the icons in one colour. On hover the colour would change to its original colour.

**Comment by SuchismitaNaik** [comment]
![sector_iconography-02](https://cloud.githubusercontent.com/assets/16536382/15053422/394d29a8-1320-11e6-8848-28c5099ee981.jpg)
Sectorial Iconography

**Comment by SuchismitaNaik** [comment]
The final home page design with both typeface: roboto and opensans

![homepage_opensans](https://cloud.githubusercontent.com/assets/16536382/16946840/476271ae-4dc9-11e6-94c1-c1acfebdf9cd.jpg)
![home_pg_roboto](https://cloud.githubusercontent.com/assets/16536382/16946841/4762d536-4dc9-11e6-98b5-77a25171d91f.jpg)

**Comment by SuchismitaNaik** [comment]
Level of governance page: 1st: Small icon and brief description 2nd: Expanded view on clicking more

![level_of_governance_pg](https://cloud.githubusercontent.com/assets/16536382/16986876/a68c70c0-4ea6-11e6-9614-c097de0df80b.jpg)
![expanded_log](https://cloud.githubusercontent.com/assets/16536382/16986875/a67e2e16-4ea6-11e6-88ac-bea57ceede5a.jpg)
